version: "3.2"
services:
  tethys:
    container_name: geoglows
    image: geoglows:latest
    volumes:
      - /home/tethys/geoglows/tethys_files:/usr/lib/tethys
      - /home/tethys/geoglows/tethys/thredds:/usr/lib/tethys/thredds
    build:
      cache_from:
        - tethysplatform/tethys-core
      context: ../
    ports:
      - "8004:80"
    environment:
      TETHYS_DB_SUPERUSER: "tethys_super"
      TETHYS_DB_SUPERUSER_PASS: "pass"
      ASGI_PROCESSES: 4
      CLIENT_MAX_BODY_SIZE: "75M"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: geoglows_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - /home/tethys/geoglows/pgdata:/var/lib/postgresql/data
