# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tethys_config', '0002_appproxyinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appproxyinstance',
            name='description',
            field=models.TextField(blank=True, max_length=2048),
        ),
    ]
